GET /users HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ0ZjA0YjVjZDlmMmM4N2YzOTcwMmUiLCJpYXQiOjE3MTU3OTQzMTUsImV4cCI6MTcxNTc5NzkxNX0.7GHWvYkO_rf2z8F12Jdg6HxSERbAEbDTTOXPfDqwi2o